### ISSUE TITLE
Watch file changes

### ISSUE THREAD

**Issue by felipeweb** [crgimenes/goconfig#33]
reload config when file change

**Comment by crgimenes** [comment]
Reload config when the file or environment variable change :D

**Comment by washingt0** [comment]
This must be a pure go implementation or can use some external tools like [`inotify`](http://man7.org/linux/man-pages/man7/inotify.7.html)?

**Comment by crgimenes** [comment]
Just Go standard / vanilla.
Needs to be portable to other platforms so we can't use anything OS specific

**Comment by felipeweb** [comment]
We can use https://github.com/fsnotify/fsnotify that is portable

**Comment by washingt0** [comment]
Ok, I'll work on this
