### ISSUE TITLE
prefix duplicate

### ISSUE THREAD

**Issue by avelino** [crgimenes/goconfig#38]
bug generate last release (ref #35): https://github.com/crgimenes/goconfig/releases/tag/v1.2.0
normal working on: https://github.com/crgimenes/goconfig/releases/tag/v1.1.0

example source: https://github.com/crgimenes/goconfig/blob/0833bfaf1186cae399f04b33d4a1b8c1c2b9e73b/examples/change_prefix/main.go
```
~/src/github.com/crgimenes/goconfig/examples/change_prefix/ master
λ go run main.go -h
Usage
  -domain string

  -mongo_host string
         (default "example.com")
  -mongo_port int
         (default 999)
  -user_name string

  -user_passwd string

Environment variables:
  $EXAMPLE_DOMAIN string

  $EXAMPLE_USER_EXAMPLE_NAME string

  $EXAMPLE_USER_EXAMPLE_PASSWD string

  $EXAMPLE_MONGO_EXAMPLE_HOST string
        (default "example.com")
  $EXAMPLE_MONGO_EXAMPLE_PORT int
        (default "999")

exit status 2
```

`EXAMPLE_MONGO_EXAMPLE_HOST` correct is `EXAMPLE_MONGO_HOST`

**Comment by crgimenes** [comment]
Thank you for the excellent description of the problem. I think everything is ok now.
